name: Keep Renote Alive

on:
  schedule:
    - cron: "*/4 * * * *"  # Toutes les 4 minutes
  workflow_dispatch:        # Lancement manuel possible

jobs:
  ping:
    runs-on: ubuntu-latest
    steps:
      - name: Ping Renote
        run: |
          echo "Ping 1..."
          curl -s -o /dev/null -w "Status: %{http_code} | Time: %{time_total}s\n" https://renote-fr.onrender.com/site-access
          
          sleep 10
          
          echo "Ping 2..."
          curl -s -o /dev/null -w "Status: %{http_code} | Time: %{time_total}s\n" https://renote-fr.onrender.com/site-access
          
          sleep 10
          
          echo "Ping 3..."
          curl -s -o /dev/null -w "Status: %{http_code} | Time: %{time_total}s\n" https://renote-fr.onrender.com/
          
          echo "Renote est bien réveillé ✅"
